#! /usr/bin python3

""" Hieroglyphic Luwian script converter

This scripts allows the user to convert between the latinized transliteration
of Hieroglyphic Luwian and the Hieroglyphic Luwian Script itself with (almost) simple rules.

The file can be imported as a module and contains the following functions:
    alpha_to_luwian - returns a converted string in Hieroglyphic Luwian script from
    a romanized string.
    luwian_to_alpha - returns a converted string in romanized linear B from a
    string in Hieroglyphic Luwian Script. (!!! WILL RETURN PROBLEMATIC DATA DUE 
    TO DOUBLE READINGS FOR THE SAME GRAPHEME IN HIEROGLYPHIC LUWIAN)

It also contains a dictionary:
    script - contains the equivalences between romanized and Hieroglyphic Luwian scripts.

Usage example:
    > a = ["MAGNUS.REX MAGNUS-TONITRUS MAGNUS.REX HEROS ka-ra-ka-mi-sà REGIO REX",
    >      "???-pa-VIR-ti-sa MAGNUS.REX HEROS INFANS-ní-mu-za",
    >      "wa-tu-tá-a CORNU-ra-ti REGIO LIS arha'-SPHINX"]
    > b = [alpha_to_luwian(i) for i in a]
    > for i in b:
    >     print(i)
    + 𔐒  𔖙𔓢  𔐒  𔐕  𔗧𔖱𔗧𔖻𔑶  𔔆  𔐑
    + X𔕸𔕠𔑣𔗔  𔐒  𔐕  𔐰𔓵𔑾𔖪
    + 𔗬𔑢𔐞𔗷  𔒂𔖱𔑣  𔔆  𔐘  𔓹𔒒
    > for i in b:
    >     print(luwian_to_alpha(i)) # NOTICE THE ERRORS
    + EXPECT ERRORS, THIS FUNCTION IS EXPERIMENTAL
    + MAGNUS.REX MAGNUS-TONITRUS MAGNUS.REX HEROS ka-ra-ka-4-CAPRA REGIO REX
    + EXPECT ERRORS, THIS FUNCTION IS EXPERIMENTAL
    + ???-pa-VIR-PES-sa MAGNUS.REX HEROS INFANS-ní-BOS+MI-za
    + EXPECT ERRORS, THIS FUNCTION IS EXPERIMENTAL
    + wa-tu-tá-a CORNU-ra-PES REGIO LIS FINES+ha-SPHINX

"""

from tools import get_key

script = {
    "EGO" : "𔐀",
    "EGO2" : "𔐁",
    "*003" : "𔐂",
    "MONS2" : "𔐃",
    "*005" : "𔐄",
    "ADORARE" : "𔐅",
    "EDERE" : "𔐆",
    "BIBERE" : "𔐇",
    "AMPLECTI" : "𔐈",
    "CAPUT" : "𔐉",
    "CAPUT+SCALPRUM" : "𔐊",
    "*011" : "𔐋",
    "STATUA" : "𔐌",
    "*013" : "𔐍",
    "pari" : "𔐎",
    "PRAE" : "𔐎",
    "DOMINA" : "𔐏",
    "MAGNUS.DOMINA" : "𔐐",
    "REX" : "𔐑",
    "MAGNUS.REX" : "𔐒",
    "á" : "𔐓",
    "*020" : "𔐔",
    "HEROS" : "𔐕",
    "LOQUI" : "𔐖",
    "*023" : "𔐗",
    "LIS" : "𔐘",
    "OCULUS" : "𔐙",
    "FRONS" : "𔐚",
    "VERSUS" : "𔐛",
    "LIBARE" : "𔐜",
    "FORTIS" : "𔐝",
    "tá" : "𔐞",
    "*030" : "𔐟",
    "PUGNUS+PUGNUS" : "𔐠",
    "LIGARE" : "𔐠",
    "BRACCHIUM" : "𔐡",
    "*033" : "𔐢",
    "POST" : "𔐣",
    "na" : "𔐤",
    "LITUS+na" : "𔐥",
    "*037" : "𔐦",
    "*038" : "𔐧",
    "PUGNUS" : "𔐨",
    "PUGNUS+x" : "𔐩",
    "*040" : "𔐪",
    "tà" : "𔐫",
    "CAPERE" : "𔐫",
    "tà'" : "𔐬",
    "ta-x" : "𔐭",
    "CAPERE2.CAPERE2" : "𔐭",
    "CAPERE2" : "𔐮",
    "*044" : "𔐯",
    "INFANS" : "𔐰",
    "FILIUS" : "𔐰",
    "FRATER" : "𔐰",
    "FILIA" : "𔐱",
    "REX.INFANS.FILIUS" : "𔐲",
    "REX.FILIUS" : "𔐲",
    "REX.FILIA" : "𔐳",
    "MAGNUS.FILIA" : "𔐴",
    "*047" : "𔐵",
    "*048" : "𔐶",
    "a+tá" : "𔐷",
    "*050" : "𔐸",
    "*051" : "𔐹",
    "MANUS.CULTER" : "𔐺",
    "ENSIS" : "𔐻",
    "MANUS+CULTER" : "𔐻",
    "*054" : "𔐼",
    "nì" : "𔐽",
    "ká" : "𔐾",
    "ká'" : "𔐿",
    "SUB" : "𔐿",
    "INFRA" : "𔐿",
    "CUM" : "𔑀",
    "MANUS" : "𔑁",
    "*060" : "𔑂",
    "*061" : "𔑃",
    "MANUS+MINUS" : "𔑄",
    "LONGUS" : "𔑄",
    "*063" : "𔑅",
    "*064" : "𔑆",
    "PONERE" : "𔑇",
    "DARE" : "𔑈",
    "pi" : "𔑈",
    "pi'" : "𔑉",
    "DARE.DARE" : "𔑊",
    "MANDARE" : "𔑊",
    "MANDARE2" : "𔑋",
    "*067" : "𔑌",
    "*068" : "𔑍",
    "*069" : "𔑎",
    "SUPER" : "𔑏",
    "sari" : "𔑏",
    "sara" : "𔑏",
    "*071" : "𔑐",
    "*072" : "𔑑",
    "AURIS+tu+mi" : "𔑒",
    "AUDIRE+tu+mi" : "𔑒",
    "*074" : "𔑓",
    "*075" : "𔑔",
    "*076" : "𔑕",
    "*077" : "𔑖",
    "ALA" : "𔑗",
    "FEMINA" : "𔑘",
    "MATER" : "𔑘",
    "SARMA" : "𔑙",
    "SARMA2" : "𔑚",
    "ta6" : "𔑛",
    "CRUS" : "𔑛",
    "CRUS+FLUMEN" : "𔑜",
    "CRUS2" : "𔑝",
    "nà" : "𔑝",
    "GENUFLECTERE" : "𔑞",
    "CRUS.CRUS" : "𔑟",
    "*087" : "𔑠",
    "*088" : "𔑡",
    "tu" : "𔑢",
    "PES" : "𔑣",
    "ti" : "𔑣",
    "PES.SCALA.ROTAE" : "𔑤",
    "*092" : "𔑥",
    "PES2" : "𔑦",
    "*094" : "𔑧",
    "PES2.PES2" : "𔑨",
    "PES2.PES" : "𔑩",
    "LEO" : "𔑪",
    "BESTIA" : "𔑪",
    "LEO2" : "𔑫",
    "CANIS" : "𔑬",
    "CANIS2" : "𔑭",
    "EQUUS" : "𔑮",
    "ASINUS" : "𔑯",
    "ta" : "𔑯",
    "ta'" : "𔑰",
    "ASINUS2" : "𔑱",
    "ASINUS2A" : "𔑲",
    "CERVUS" : "𔑳",
    "rú" : "𔑳",
    "CERVUS2" : "𔑴",
    "rú'" : "𔑴",
    "rú''" : "𔑵",
    "CERVUS3" : "𔑵",
    "CAPRA" : "𔑶",
    "sà" : "𔑶",
    "sà'" : "𔑷",
    "CAPRA2" : "𔑸",
    "sà''" : "𔑸",
    "CAPRA2A" : "𔑹",
    "sà'''" : "𔑹",
    "BOS" : "𔑺",
    "u" : "𔑺",
    "BOS'" : "𔑻",
    "u'" : "𔑻",
    "BOS2" : "𔑼",
    "u''" : "𔑼",
    "*106" : "𔑽",
    "BOS+MI" : "𔑾",
    "mu" : "𔑾",
    "muwa" : "𔑾",
    "mu'" : "𔑿",
    "muwa'" : "𔑿",
    "BOS.MI" : "𔒀",
    "mu''" : "𔒀",
    "muwa''" : "𔒀",
    "BOS2.MI" : "𔒁",
    "mu'''" : "𔒁",
    "muwa'''" : "𔒁",
    "CORNU" : "𔒂",
    "sú" : "𔒂",
    "VITELLUS" : "𔒃",
    "ma-x" : "𔒃",
    "OVIS" : "𔒄",
    "ma" : "𔒄",
    "ma'" : "𔒅",
    "OVIS2" : "𔒆",
    "ma''" : "𔒆",
    "OVIS3" : "𔒇",
    "LINGERE" : "𔒈",
    "za4" : "𔒈",
    "*113" : "𔒉",
    "LITUUS+U" : "𔒊",
    "LEPUS" : "𔒋",
    "tapa" : "𔒋",
    "LEPUS2" : "𔒌",
    "tapa'" : "𔒌",
    "*116" : "𔒍",
    "*117" : "𔒎",
    "*118" : "𔒏",
    "*119" : "𔒐",
    "GRYLLUS" : "𔒑",
    "SPHINX" : "𔒒",
    "*122" : "𔒓",
    "*123" : "𔒔",
    "*124" : "𔒕",
    "lí'" : "𔒖",
    "UNGULA" : "𔒗",
    "li-x" : "𔒗",
    "*126" : "𔒘",
    "*127" : "𔒙",
    "AVIS" : "𔒚",
    "zi4" : "𔒚",
    "*129" : "𔒛",
    "AVIS3" : "𔒜",
    "AVIS5" : "𔒝",
    "AVIS2" : "𔒞",
    "AQUILA" : "𔒟",
    "AVIS4" : "𔒟",
    "ara" : "𔒟",
    "ari" : "𔒟",
    "ara'" : "𔒠",
    "ari'" : "𔒠",
    "AVIS-x" : "𔒡",
    "*135A" : "𔒢",
    "*136" : "𔒣",
    "LIBATIO" : "𔒤",
    "PISCIS" : "𔒥",
    "*139" : "𔒦",
    "*140" : "𔒧",
    "*141" : "𔒨",
    "*142" : "𔒩",
    "*143" : "𔒪",
    "*144" : "𔒫",
    "*145" : "𔒬",
    "*146" : "𔒭",
    "*147" : "𔒮",
    "JANUS" : "𔒯",
    "*149" : "𔒰",
    "*150" : "𔒱",
    "TELIPINU" : "𔒲",
    "*152" : "𔒳",
    "nu" : "𔒴",
    "*154" : "𔒵",
    "*155" : "𔒶",
    "*156" : "𔒷",
    "*157" : "𔒸",
    "*158" : "𔒹",
    "*159" : "𔒺",
    "VITIS" : "𔒻",
    "wi'" : "𔒻",
    "wi(ya)" : "𔒻",
    "*161" : "𔒼",
    "*162" : "𔒽",
    "*163" : "𔒾",
    "*164" : "𔒿",
    "BONUS" : "𔓀",
    "wà" : "𔓀",
    "wì" : "𔓀",
    "wá" : "𔓁",
    "wí" : "𔓁",
    "*167" : "𔓂",
    "*168" : "𔓃",
    "*169" : "𔓄",
    "*170" : "𔓅",
    "*171" : "𔓆",
    "ta5" : "𔓇",
    "ti5" : "𔓇",
    "lá" : "𔓇",
    "lí" : "𔓇",
    "HASTARIUS" : "𔓈",
    "si" : "𔓉",
    "LINGUA" : "𔓊",
    "la" : "𔓊",
    "la+la" : "𔓋",
    "LINGUA+CLAVUS" : "𔓌",
    "la+ra+a" : "𔓍",
    "HORDEUM" : "𔓎",
    "hwi-x" : "𔓎",
    "*180" : "𔓏",
    "PANIS" : "𔓐",
    "pa-x" : "𔓐",
    "CAELUM" : "𔓑",
    "*183" : "𔓒",
    "*184" : "𔓓",
    "*185" : "𔓔",
    "*186" : "𔓕",
    "*187" : "𔓖",
    "*188" : "𔓗",
    "*189" : "𔓘",
    "SOL2" : "𔓙",
    "SOL" : "𔓚",
    "ORIENS" : "𔓛",
    "LUNA" : "𔓜",
    "*194" : "𔓝",
    "*195" : "𔓞",
    "HATTI" : "𔓟",
    "há" : "𔓟",
    "HATTI+LI" : "𔓠",
    "HATTUSILI" : "𔓠",
    "há-li" : "𔓠",
    "*198" : "𔓡",
    "TONITRUS" : "𔓢",
    "FULGUR" : "𔓣",
    "TERRA" : "𔓤",
    "LOCUS" : "𔓤",
    "wa6" : "𔓤",
    "wi6" : "𔓤",
    "VIA+TERRA.SCALPRUM" : "𔓥",
    "VIA+TERRA+SCALPRUM" : "𔓦",
    "(DEUS)VIA+TERRA" : "𔓧",
    "*203" : "𔓨",
    "wa5" : "𔓩",
    "wi5" : "𔓩",
    "*205" : "𔓪",
    "*206" : "𔓫",
    "MONS" : "𔓬",
    "wa5'" : "𔓬",
    "wi5'" : "𔓬",
    "LEO+MONS.tu+LEO" : "𔓭",
    "*208" : "𔓮",
    "i" : "𔓯",
    "i(a)" : "𔓯",
    "i+ra" : "𔓰",
    "i+ri" : "𔓰",
    "ia" : "𔓱",
    "*211" : "𔓲",
    "FLUMEN" : "𔓳",
    "*213" : "𔓴",
    "ní" : "𔓵",
    "FONS" : "𔓶",
    "ha" : "𔓷",
    "FINES" : "𔓸",
    "arha" : "𔓸",
    "FINES+ha" : "𔓹",
    "arha'" : "𔓹",
    "*217" : "𔓺",
    "*218" : "𔓻",
    "*219" : "𔓼",
    "*220" : "𔓽",
    "VIA" : "𔓾",
    "*222" : "𔓿",
    "sa6" : "𔔀",
    "*224" : "𔔁",
    "URBS" : "𔔂",
    "ISHUWA" : "𔔃",
    "*227" : "𔔄",
    "URBS+li" : "𔔅",
    "URBS-li" : "𔔅",
    "MURSILI" : "𔔅",
    "REGIO" : "𔔆",
    "tu4" : "𔔆",
    "mí.REGIO" : "𔔇",
    "*230" : "𔔈",
    "CASTRUM" : "𔔉",
    "*232" : "𔔊",
    "*233" : "𔔋",
    "*234" : "𔔌",
    "*235" : "𔔍",
    "*236" : "𔔎",
    "PORTA" : "𔔏",
    "*238" : "𔔐",
    "PORTA2" : "𔔑",
    "*240" : "𔔒",
    "ki-x" : "𔔓",
    "*242" : "𔔔",
    "CUBITUM" : "𔔕",
    "AEDIFICIUM" : "𔔖",
    "VACUUS" : "𔔗",
    "AEDIFICIUM+MINUS" : "𔔗",
    "AEDIFICARE" : "𔔘",
    "AEDIFICIUM.PONERE" : "𔔘",
    "DOMUS" : "𔔙",
    "DELERE" : "𔔚",
    "DOMUS+MINUS" : "𔔚",
    "DEUS.DOMUS" : "𔔛",
    "MAGNUS.DOMUS" : "𔔜",
    "DOMUS+x" : "𔔝",
    "DOMUS+SCALA" : "𔔞",
    "*253" : "𔔟",
    "EUNUCHUS2" : "𔔠",
    "HORREUM" : "𔔡",
    "*256" : "𔔢",
    "ARGENTUM" : "𔔣",
    "*258" : "𔔤",
    "*259" : "𔔥",
    "*260" : "𔔦",
    "*261" : "𔔧",
    "*262" : "𔔨",
    "*263" : "𔔩",
    "PODIUM" : "𔔪",
    "*265" : "𔔫",
    "PES.REGIO" : "𔔬",
    "STELE" : "𔔭",
    "LAPIS+SCALPRUM" : "𔔭",
    "LAPIS" : "𔔮",
    "SCALPRUM" : "𔔯",
    "EXERCITUS" : "𔔰",
    "*270" : "𔔱",
    "*271" : "𔔲",
    "SCUTUM" : "𔔳",
    "*273" : "𔔴",
    "*274" : "𔔵",
    "*275" : "𔔶",
    "FRATER2" : "𔔷",
    "IUDEX.la" : "𔔸",
    "IUDEX+la" : "𔔸",
    "li" : "𔔹",
    "*279" : "𔔺",
    "MALLEUS" : "𔔻",
    "wa9" : "𔔻",
    "wi9" : "𔔻",
    "ASCIA" : "𔔼",
    "*282" : "𔔽",
    "tuzzi" : "𔔾",
    "*284" : "𔔿",
    "IACULUM" : "𔕀",
    "*285" : "𔕀",
    "zuwa" : "𔕀",
    "wa7" : "𔕁",
    "wi7" : "𔕁",
    "*287" : "𔕂",
    "CURRUS" : "𔕃",
    "AURIGA" : "𔕄",
    "AURIGA2" : "𔕅",
    "hara" : "𔕆",
    "hari" : "𔕆",
    "lì" : "𔕇",
    "ROTA" : "𔕈",
    "hala" : "𔕈",
    "hali" : "𔕈",
    "*293" : "𔕉",
    "THRONUS" : "𔕊",
    "MENSA" : "𔕊",
    "THRONUS'" : "𔕋",
    "MENSA2" : "𔕋",
    "SARPA" : "𔕋",
    "SOL2.THRONUS/MENSA" : "𔕌",
    "*295" : "𔕌",
    "(DEUS)MONS.SARPA" : "𔕍",
    "(DEUS)MONS.MENSA" : "𔕍",
    "THRONUS''" : "𔕍",
    "*297" : "𔕎",
    "THRONUS2" : "𔕏",
    "SOLIUM" : "𔕐",
    "í" : "𔕐",
    "iá" : "𔕑",
    "NEPOS" : "𔕒",
    "LECTUS" : "𔕓",
    "*302" : "𔕔",
    "SARA" : "𔕕",
    "SARI" : "𔕕",
    "mà" : "𔕖",
    "FUSUS" : "𔕗",
    "hí" : "𔕘",
    "hu" : "𔕙",
    "*308" : "𔕚",
    "CRUX" : "𔕛",
    "CRUX2" : "𔕜",
    "*310" : "𔕝",
    "*311" : "𔕞",
    "*312" : "𔕟",
    "VIR" : "𔕠",
    "zí" : "𔕠",
    "ha-x" : "𔕡",
    "kar" : "𔕢",
    "sa7" : "𔕣",
    "*317" : "𔕤",
    "TESHUB" : "𔕥",
    "ta4" : "𔕦",
    "ti4" : "𔕦",
    "la'" : "𔕦"   ,
    "li'" : "𔕦",
    "*320" : "𔕧",
    "*321" : "𔕨",
    "PURUS" : "𔕩",
    "*323" : "𔕪",
    "*324" : "𔕫",
    "tú" : "𔕬",
    "SCRIBA" : "𔕭",
    "tù" : "𔕭",
    "SIGILLUM" : "𔕮",
    "sa5" : "𔕮",
    "pu" : "𔕯",
    "REL" : "𔕰",
    "kwi" : "𔕰",
    "kwa" : "𔕰",
    "*329A" : "𔕱",
    "CAPERE+SCALPRUM" : "𔕲",
    "AVUS" : "𔕳",
    "NEG" : "𔕴",
    "NEG2" : "𔕵",
    "ná" : "𔕵",
    "NEG3" : "𔕶",
    "*333" : "𔕷",
    "pa" : "𔕸",
    "zá" : "𔕹",
    "ANNUS" : "𔕺",
    "PITHOS.SCUTELLA" : "𔕺",
    "PITHOS" : "𔕺",
    "zì" : "𔕺",
    "zì'" : "𔕻",
    "zà" : "𔕼",
    "za-x" : "𔕽",
    "PITHOS'" : "𔕾",
    "CULTER" : "𔕿",
    "*339" : "𔖀",
    "ANNUS+ANNUS" : "𔖁",
    "VAS" : "𔖂",
    "*342" : "𔖃",
    "PITHOS''" : "𔖄",
    "CONTRACTUS" : "𔖅",
    "URCEUS" : "𔖆",
    "POCULUM" : "𔖇",
    "hú" : "𔖈",
    "*348" : "𔖉",
    "*349" : "𔖊",
    "*350" : "𔖋",
    "*351" : "𔖌",
    "*352" : "𔖍",
    "*353" : "𔖎",
    "*354" : "𔖏",
    "SACERDOS" : "𔖐",
    "*356" : "𔖑",
    "*357" : "𔖒",
    "DIES" : "𔖓",
    "*359" : "𔖔",
    "*359A" : "𔖕",
    "DEUS" : "𔖖",
    "*361" : "𔖗",
    "má" : "𔖘",
    "MAGNUS" : "𔖙",
    "ur" : "𔖙",
    "u'''" : "𔖚",
    "mu''''" : "𔖛",
    "*365" : "𔖜",
    "OMNIS(+mi)" : "𔖝",
    "tala" : "𔖞",
    "MALUS" : "𔖟",
    "MALUS2" : "𔖠",
    "VITA" : "𔖡",
    "BONUS2" : "𔖢",
    "su" : "𔖢",
    "IUSTITIA" : "𔖣",
    "IUDEX" : "𔖣",
    "IUDEX+ra" : "𔖤",
    "IUDEX+ri" : "𔖤",
    "IUDEX+tara" : "𔖤",
    "IUDEX+tari" : "𔖤",
    "SACERDOS2" : "𔖥",
    "*373" : "𔖦",
    "*374" : "𔖧",
    "*375" : "𔖨",
    "zi" : "𔖩",
    "za'" : "𔖩",
    "za" : "𔖪",
    "LITUUS" : "𔖫",
    "OCCIDENS" : "𔖬",
    "ià" : "𔖬",
    "1" : "𔖭",
    "UNUS" : "𔖭",
    "sa8" : "𔖭",
    "MINUS" : "𔖮",
    "MORI" : "𔖯",
    "VI2.MINUS" : "𔖯",
    "lignum" : "𔖰",
    "ra" : "𔖱",
    "ri" : "𔖱",
    "'" : "𔖲",
    "2" : "𔖳",
    "2'" : "𔖴",
    "VIR2" : "𔖵",
    "WD" : "𔖵",
    "VIR2A" : "𔖶",
    "SERVUS" : "𔖷",
    "mì" : "𔖷",
    "3" : "𔖸",
    "tara'" : "𔖸",
    "tari'" : "𔖸",
    "tara" : "𔖹",
    "tari" : "𔖹",
    "DOMINUS" : "𔖺",
    "4" : "𔖻",
    "mi" : "𔖻",
    "5" : "𔖼",
    "8" : "𔖽",
    "*394" : "𔖾",
    "9" : "𔖿",
    "nú" : "𔖿",
    "*396" : "𔗀",
    "10" : "𔗁",
    "DECEM" : "𔗁",
    "*398" : "𔗂",
    "100" : "𔗃",
    "CENTUM" : "𔗃",
    "1000" : "𔗄",
    "MILLE" : "𔗄",
    "*401" : "𔗅",
    "SCUTELLA" : "𔗆",
    "sa4" : "𔗆",
    "*403" : "𔗇",
    "ANIMAL" : "𔗈",
    "*405" : "𔗉",
    "*406" : "𔗊",
    "*407" : "𔗋",
    "*408" : "𔗌",
    "*409" : "𔗍",
    "<" : "𔗎",
    ">" : "𔗏",
    "ni" : "𔗐",
    "ru" : "𔗑",
    "hi" : "𔗒",
    "*414" : "𔗓",
    "sa" : "𔗔",
    "*416" : "𔗕",
    "sa-x" : "𔗖",
    "*418" : "𔗗",
    "mí" : "𔗘",
    "urhi" : "𔗘",
    "*420" : "𔗙",
    "us" : "𔗚",
    "PANIS.SCUTELLA" : "𔗛",
    "ku" : "𔗜",
    "*424" : "𔗝",
    "*425" : "𔗞",
    "*426" : "𔗟",
    "*427" : "𔗠",
    "*428" : "𔗡",
    "tana" : "𔗢",
    "OMNIS2" : "𔗣",
    "pú" : "𔗣",
    "*431" : "𔗤",
    "*432" : "𔗥",
    "sá" : "𔗦",
    "ka" : "𔗧",
    "a-x" : "𔗨",
    "*436" : "𔗩",
    "*437" : "𔗪",
    "PASTOR" : "𔗫",
    "wa" : "𔗬",
    "wi" : "𔗬",
    "*440" : "𔗭",
    "*441" : "𔗮",
    "*442" : "𔗯",
    "*443" : "𔗰",
    "*444" : "𔗱",
    "la''" : "𔗲",
    "li''" : "𔗲",
    "lu" : "𔗲",
    "ki" : "𔗳",
    "ni-x" : "𔗴",
    "*448" : "𔗵",
    "*449" : "𔗶",
    "a" : "𔗷",
    "WE" : "𔗷",
    "a+ra" : "𔗸",
    "a+ri" : "𔗸",
    "huru" : "𔗹",
    "*452" : "𔗺",
    "*453" : "𔗻",
    "*454" : "𔗼",
    "la-x" : "𔗽",
    "sí-x" : "𔗾",
    "*457" : "𔗿",
    "*457A" : "𔘀",
    "*458" : "𔘁",
    "*459" : "𔘂",
    "*460" : "𔘃",
    "ma-x'" : "𔘄",
    "*462" : "𔘅",
    "*463" : "𔘆",
    "*464" : "𔘇",
    "*465" : "𔘈",
    "*466" : "𔘉",
    "*467" : "𔘊",
    "*468" : "𔘋",
    "*469" : "𔘌",
    "12" : "𔘍",
    "*471" : "𔘎",
    "*472" : "𔘏",
    "*473" : "𔘐",
    "EUNUCHUS" : "𔘑",
    "*475" : "𔘒",
    "*476" : "𔘓",
    "*477" : "𔘔",
    "*478" : "𔘕",
    "*479" : "𔘖",
    "*480" : "𔘗",
    "*481" : "𔘘",
    "*482" : "𔘙",
    "*483" : "𔘚",
    "*484" : "𔘛",
    "*485" : "𔘜",
    "*486" : "𔘝",
    "*487" : "𔘞",
    "tí" : "𔘟",
    "*489" : "𔘠",
    "*490" : "𔘡",
    "*491" : "𔘢",
    "*492" : "𔘣",
    "*493" : "𔘤",
    "*494" : "𔘥",
    "*495" : "𔘦",
    "*496" : "𔘧",
    "*497" : "𔘨",
    "*501" : "𔘩",
    "*502" : "𔘪",
    "*503" : "𔘫",
    "*504" : "𔘬",
    "*505" : "𔘭",
    "hana" : "𔘮",
    "*507" : "𔘯",
    "CURRERE" : "𔘰",
    "hwi'" : "𔘰",
    "hwa'" : "𔘰",
    "*509" : "𔘱",
    "*510" : "𔘲",
    "*511" : "𔘳",
    "*512" : "𔘴",
    "*513" : "𔘵",
    "*514" : "𔘶",
    "*515" : "𔘷",
    "*516" : "𔘸",
    "*517" : "𔘹",
    "*518" : "𔘺",
    "*519" : "𔘻",
    "*520" : "𔘼",
    "*521" : "𔘽",
    "*522" : "𔘾",
    "*523" : "𔘿",
    "PROPHETA" : "𔙀",
    "CORNU+CAPUT" : "𔙀",
    "PRINCEPS" : "𔙁",
    "*526" : "𔙂",
    "APER" : "𔙃",
    "tì" : "𔙄",
    "LINGUA-x" : "𔙅",
    "*530" : "𔙆",
    "???": "X"
        }


def alpha_to_luwian(input):
    """ Converts text in Latin Alphabet to Hieroglyphic Luwian Script

    Each syllable should be separated by a sing dash, each word by a space.

    Parameters
    ----------
    input : str
        Text input with syllables separated by dashes and words by spaces.

    Returns
    -------
    output : str
        Transliterated text in Hieroglyphic Luwian Script

    Usage
    -----
    
    > alpha_to_luwian("EGO-mi u'-ra-hi-li-na")
    + '𔐀𔖻  𔑻𔖱𔗒𔔹𔐤'

    """

    output = []
    input = input.split(" ")
    for word in input:
        word_out = ""
        if word.isnumeric():
            word = [int(i) for i in word]
            tens = [10**n for n in range(len(word)-1,-1,-1)]
            for i in range(len(tens)):
                word_out = word_out + script[str(word[i]*tens[i])]
        elif "-" in word:
            for syllabe in word.split("-"):
                word_out = word_out + script[syllabe]
        else:
            word_out = script[word]

        output.append(word_out)

    return "  ".join(output)


def luwian_to_alpha(input, warnings=True):
    """ Converts text in Hieroglyphic Luwian Script to Latin Alphabet

    Some warnings might occur if a syllable has multiple values.

    Parameters
    ----------
    input : str
        Text input in Hieroglyphic Luwian Script
    warnings : bool
        Reminds that the function is VERY experimental.
        Defaults to true

    Returns
    -------
    output : str
        Transliterated text in Latin Alphabet

    Usage
    -----
    
    > luwian_to_alpha("𔐀𔖻  𔑻𔖱𔗒𔔹𔐤")
    + EXPECT ERRORS, THIS FUNCTION IS EXPERIMENTAL
    + EGO-4 BOS'-ra-hi-li-na
    > luwian_to_alpha("𔐀𔖻  𔑻𔖱𔗒𔔹𔐤", warnings=False) # The output is still wrong
    + EGO-4 BOS'-ra-hi-li-na
    """
    
    if warnings:
        print("EXPECT ERRORS, THIS FUNCTION IS EXPERIMENTAL")

    output = []
    input = input.split()
    for word in input:
        word_out = ""
        if len(word) > 1:
            syllabes = [sy for sy in word]
            for syllabe in syllabes:
                word_out = word_out + get_key(syllabe, script) + "-"
            word_out = str(word_out)
            if len(word_out) > 1 and word_out[-1] == "-":
                word_out = word_out[:-1]
        else:
            word_out = get_key(word, script)
        output.append(word_out)
        for i in range(len(output)):
            if output[i].split("-")[0].isnumeric():
                output[i] = str(sum([int(i) for i in output[i].split("-")]))

    return " ".join(output)

if __name__ == "__main__":
    a = ["MAGNUS.REX MAGNUS-TONITRUS MAGNUS.REX HEROS ka-ra-ka-mi-sà REGIO REX",
         "???-pa-VIR-ti-sa MAGNUS.REX HEROS INFANS-ní-mu-za",
         "wa-tu-tá-a CORNU-ra-ti REGIO LIS arha'-SPHINX"]
    b = [alpha_to_luwian(i) for i in a]
    for i in b:
        print(i)

    for i in b:
        print(luwian_to_alpha(i))
        
